### ISSUE TITLE
Failed with my own .midi file

### ISSUE THREAD

**Issue by huqinhan1997** [bwang514/PerformanceNet#1]
Hi, your work was amazing! I am reproducing it but I got some problems when using my own cello solo midi file to run the synthesize_audio.sh.

At first, the ERROR was : 
**TypeError: conv1d(): argument 'input' (position 1) must be Tensor, not numpy.ndarray**
Then I turned score and onoff to Tensor, but not fixed, the error was:
**RuntimeError: input has less dimensions than expected**
I found that my midi file's shape is **torch.Size([22277, 128])**, while your TEST_DATA is **torch.Size([5, 128, 860])**
I tried other midi files but also got same problems. So  maybe the process_custom_midi function not transform the midi file with suitable shape?

Again, I appreciate your time reading this issue.  Have a great day!

**Comment by bwang514** [comment]
Can you try resize your input to ([1, 22277, 128]) ?

**Comment by huqinhan1997** [comment]
@bwang514 I tried like this
<img width="737" alt="截屏2020-03-0416 48 19" src="https://user-images.githubusercontent.com/41865022/75861162-f67fbc00-5e37-11ea-8e17-78918ae0e327.png">
**But the new error is:**
Traceback (most recent call last):
  File "/Users/huqinhan/Desktop/Graduate/PerformanceNet/scripts/../src/inference.py", line 135, in <module>
    main()
  File "/Users/huqinhan/Desktop/Graduate/PerformanceNet/scripts/../src/inference.py", line 131, in main
    AudioSynth.inference()
  File "/Users/huqinhan/Desktop/Graduate/PerformanceNet/scripts/../src/inference.py", line 75, in inference
    test_results = model(score, onoff)
  File "/Library/anaconda3/envs/performancenet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/huqinhan/Desktop/Graduate/PerformanceNet/src/model.py", line 203, in forward
    x, before_pool = module(x)
  File "/Library/anaconda3/envs/performancenet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/huqinhan/Desktop/Graduate/PerformanceNet/src/model.py", line 46, in forward
    x = self.activation(self.conv1_BN(self.conv1(x)))
  File "/Library/anaconda3/envs/performancenet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/Library/anaconda3/envs/performancenet/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 176, in forward
    self.padding, self.dilation, self.groups)
**RuntimeError: Given groups=1, weight[256, 128, 3], so expected input[1, 22277, 128] to have 128 channels, but got 22277 channels instead**

**Comment by bwang514** [comment]
Looks like there are some dimension problems. Perhaps try to resize it to (128, 22277, 128).

**Comment by bwang514** [comment]
Did you manage to solve the problem? @huqinhan1997

**Comment by huqinhan1997** [comment]
Yeah! It worked but the output wav sounded much worse than the original midi. I am trying to solve it but   I don't have a clear solution yet.

**Comment by bwang514** [comment]
The model might have a hard time rendering audio if the notes in your midi were never seen in training data. For example, if all the songs in your training data are in C major, it’s not gonna now how to play the ‘black keys’ as they never appear in the training data. Also if the notes in your midi are out of the range of the instrument you trained, it also won’t render anything.

**Comment by huqinhan1997** [comment]
That's helpful, thanks! I would keep working on it.
